# Generated by Django 4.2.6 on 2023-11-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
